import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import NavBar from "./ui/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arrow Cloud Explorer",
  description: "Generated by tfjackc",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
      <Providers>
          <div className="flex flex-col">
              <NavBar />
              {children}
          </div>
      </Providers>
      </body>
    </html>
  );
}
